"""fix tables

Revision ID: 4eb66d639c93
Revises: 37a82abfd57b
Create Date: 2025-06-20 15:39:11.460592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb66d639c93'
down_revision: Union[str, None] = '37a82abfd57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('sum_actual_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sum_actual_duration')
    # ### end Alembic commands ###
